-- walk_the_store_schema.sql
-- Run this manually in pgAdmin to create the walk_the_store schema and its two tables.
-- The walk_the_store schema does NOT exist yet — run these statements in order.
-- This schema holds agent-owned data only. All Intentwise data lives in amazon_source_data (never modified).
--
-- IMPORTANT: Run manually. Claude Code will never execute database commands.

-- Step 1: Create the schema
CREATE SCHEMA IF NOT EXISTS walk_the_store;


-- Step 2: account_config — one row per active brand
-- Populated manually via SQL INSERTs (generated by /add-brand skill from Google Sheets data).
-- account_id and country_code must match the values used in amazon_source_data tables.
CREATE TABLE walk_the_store.account_config (
    id                        SERIAL PRIMARY KEY,
    brand_name                VARCHAR(255)    NOT NULL,
    account_id                BIGINT          NOT NULL,   -- matches account_id bigint in Intentwise tables
    country_code              VARCHAR(10)     NOT NULL,   -- matches country_code varchar in Intentwise tables (e.g. 'US')
    slack_channel_id          VARCHAR(50)     NOT NULL,   -- Slack channel ID for this brand's alerts
    teamwork_project_id       VARCHAR(100)    NOT NULL,   -- Teamwork project ID for completed task lookup
    account_manager_slack_id  VARCHAR(50)     NOT NULL,   -- Slack user ID for the AM (receives DMs on critical)
    drive_folder_id           VARCHAR(255),               -- Google Drive folder ID for this brand's reports
    is_active                 BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at                TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    UNIQUE (account_id, country_code)                    -- one config row per seller+marketplace combination
);


-- Step 3: daily_health_reports — one row per brand per day, written by the agent after each run
CREATE TABLE walk_the_store.daily_health_reports (
    id                    SERIAL PRIMARY KEY,
    account_config_id     INT             NOT NULL REFERENCES walk_the_store.account_config(id),
    report_date           DATE            NOT NULL,
    highest_severity      VARCHAR(20)     NOT NULL,   -- 'critical', 'warning', or 'healthy'
    findings              JSONB           NOT NULL DEFAULT '[]',
    late_shipment_rate    NUMERIC,
    valid_tracking_rate   NUMERIC,
    pre_cancel_rate       NUMERIC,
    order_defect_rate     NUMERIC,                    -- NULL until ODR table confirmed (see postgres.py)
    account_health_rating INT,
    account_status        VARCHAR(50),
    food_safety_count     INT,
    ip_complaint_count    INT,
    data_gaps             JSONB           NOT NULL DEFAULT '[]',
    created_at            TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    UNIQUE (account_config_id, report_date)           -- one report per brand per day
);
